### ISSUE TITLE
Exclusion strategy for methods?

### ISSUE THREAD

**Issue by lalpert** [julman99/gson-fire#11]
It would be useful to be able to write an ExclusionStrategy that could decide whether to skip methods, rather than always including every exposed method in the serialization.

This could be done by subclassing ExclusionStrategy to create a new class, like FireExclusionStrategy, that has a function shouldSkipMethod() as well as the ExclusionStrategy functions shouldSkipField() and shouldSkipClass(). Then when iterating over the exposed methods, they could be included only if they pass all FireExclusionStrategies.

Are you open to adding this to the library?

**Comment by julman99** [comment]
Hello Leah

This sounds like an interesting feature. I will investigate before the end
of the week on adding it based on your suggestions.

**Comment by lalpert** [comment]
Looking forward to hearing your thoughts.

**Comment by julman99** [comment]
Sorry for the delay. I will definitely add this feature. I will subclass ```ExclusionStrategy```. However, it would have to be registered on the ```GsonFireBuilder```, otherwise I won't have access to it if it gets registered on the ```GsonBuilder```. So I will create a method on the ```GsonFireBuilder``` called ```addSerializationExclusionStrategy``` that will receive a ```FireExclusionStrategy``` and take into account the method exclusion and also register the strategy on the actual ```GsonBuilder```

Please expect this to be completed before Sunday May 31st

**Comment by julman99** [comment]
Please take a look a [this](https://github.com/julman99/gson-fire/blob/1.1.0/src/test/java/io/gsonfire/gson/FireExclusionStrategyTest.java) test and let me know if that is what you are trying to achieve.

**Comment by lalpert** [comment]
Yes, looks good!

**Comment by julman99** [comment]
Ok I will do some other tests to make sure the strategies are registered on ```GsonBuilder``` and then release the new version. Hopefully I'll do it today, otherwise during the week.

Thanks again for the suggestion

**Comment by julman99** [comment]
This has been released in 1.1.0

I did a last minute change in which ```FireExclusionStrategy``` does not extends from ```ExclusionStrategy``` because it could have lead to confusion - for example people trying to register a ```FireExclusionStrategy``` to exclude methods directly on ```GsonFire```, that would compile but would not work.

Aside from that it should work as you suggested. Thanks!

**Comment by lalpert** [comment]
Thanks! It would be nice to be able to write just one ExclusionStrategy that handled both methods and fields (such as excluding methods and fields by name) but I understand why you changed it. I'll try this out soon!

**Comment by julman99** [comment]
You can, by creating a class that implements both interfaces :)

**Comment by lalpert** [comment]
Good point! But I have to register it on both the GsonFireBuilder and the GsonBuilder, right?

**Comment by julman99** [comment]
Correct
